#!/bin/bash

PDIR="${HOME}"/.config/wayfire-de/wallpapers
if [[ ! -f "${PDIR}"/.DO_ROTATE ]]; then
    exit
fi

while true; do

WP_RAW=("${PDIR}"/*)
TOTAL=${#WP_RAW[@]}

if [[ 0 -eq ${TOTAL} ]]; then
    exit
fi

# don't put newline characters in names
IFS=$'\n' WALLPAPERS=($(sort <<<"${WP_RAW[*]}"))
unset IFS

CINDEX=-1
if [[ -f "${PDIR}"/.current ]]; then
    CURRENT=$(cat "${PDIR}"/.current)
    iter=0
    for paper in "${WALLPAPERS[@]}"; do
        if [[ "${paper}" == "${CURRENT}" ]]; then
            CINDEX=$iter
            break
        fi
        iter=$((iter + 1))
    done
fi
CINDEX=$((CINDEX + 1))
CINDEX=$((CINDEX % TOTAL))
NEW_WP="${WALLPAPERS[CINDEX]}"
ogurictl output '*' --image "${NEW_WP}" || exit 1
printf %s\\n "${NEW_WP}" > "${PDIR}"/.current || exit 1

sleep 60s

done
